### ISSUE TITLE
Issues building

### ISSUE THREAD

**Issue by thefinn93** [TooTallNate/node-vorbis#19]
This is probably something I'm doing wrong, but I can't figure it out so I'm opening a issue.

When i do `npm install vorbis`, it fails with this appearing to the the important line:

```
g++: error: /tmp/oggtest/node_modules/vorbis/node_modules/ogg/build/Release/ogg.node: No such file or directory
```

([full log here](https://gist.github.com/thefinn93/66de1e7f7efd9a9446ee38e80d867e74)).

Some googling indicated my npm version (1.4.21) may be too old, so I installed the latest version (`npm install npm` for npm v3.10.8), tried again and got [this](https://gist.github.com/thefinn93/e929afe2a3220827ce86912966182b6f). And [here](https://gist.github.com/thefinn93/dc65526ebda3b2d1ca246e36a9775dc8) is the npm-debug.log file.

What am I doing wrong?

Thanks

**Comment by LinusU** [comment]
Closing this since it's been ~2 years, please feel free to reopen if it still doesn't work ☺️
