### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by LinusU** [TooTallNate/node-vorbis#21]
It would be nice to add support for ARM processors, e.g. the one used in the Raspberry Pi.

To do this, someone needs to contribute a `deps/libvorbis/config/linux/armv6l/config.h` file.

**Comment by filiptc** [comment]
Looks like the current linux64 (https://github.com/TooTallNate/node-vorbis/tree/master/deps/libvorbis/config/linux/x64/config.h) one compiles fine for armv71 (current raspi3b).
